version: 2

before:
  hooks:
    - go-licenses save ./... --save_path=./third_party_licenses --force --ignore github.com/alphaleonis/cctote
    - bash -c "go-licenses report ./... --ignore github.com/alphaleonis/cctote > ./third_party_licenses/NOTICES.csv 2>/dev/null"

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/alphaleonis/cctote/internal/buildinfo.version={{ .Tag }}

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - src: ./third_party_licenses/**/*
        dst: .
        strip_parent: false

release:
  draft: true

changelog:
  disable: true
